-- UNS-CIC-500-V1.0 compact seed. {number,title,body}
return {
{1,"Objet du Code","Le présent Code établit les règles communes de l'Union des Nations Souveraines, organise ses institutions, définit les droits et obligations de ses membres et fixe les conditions de responsabilité internationale."},
{2,"Dénomination de l'Union","L'organisation commune instituée par la Charte porte le nom d'Union des Nations Souveraines, abrégée UNS, et peut être désignée comme l'Union dans les actes officiels."},
{3,"Dénomination de la Cour","L'organe juridictionnel permanent porte le nom de Cour internationale de l'Union, abrégée CIU."},
{4,"État proposant","Le présent projet de Code est présenté à la ratification commune à l'initiative de North Coalition sans que cette qualité lui confère un privilège juridique particulier."},
{5,"Champ d'application matériel","Le Code s'applique aux matières expressément régies par ses dispositions ainsi qu'aux actes nécessaires à leur interprétation, leur exécution et leur contrôle."},
{6,"Champ d'application personnel","Le Code lie les États membres, leurs organes, leurs agents et, lorsque le texte le prévoit, les personnes physiques, organisations, entreprises et groupes placés sous leur juridiction."},
{7,"État","Est considéré comme État toute entité politique reconnue selon le présent Code, disposant d'un gouvernement identifiable et d'un territoire ou d'une implantation durable."},
{8,"Gouvernement","Le gouvernement est l'autorité qui exerce effectivement les fonctions exécutives d'un État et dont la qualité est enregistrée auprès de l'Union."},
{9,"Autorité publique","Est une autorité publique tout organe, service ou agent habilité à agir au nom d'un État, d'une collectivité reconnue ou d'une institution de l'Union."},
{10,"Organisation","Une organisation est une structure organisée distincte d'une personne physique, dotée d'un objet, de membres ou de dirigeants et d'une capacité d'action identifiable."},
{11,"Organisation internationale","Est internationale toute organisation créée ou reconnue par plusieurs États pour exercer des fonctions communes."},
{12,"Groupe armé","Est un groupe armé toute organisation disposant d'une chaîne de commandement et de moyens militaires ou paramilitaires sans constituer une force régulière reconnue d'un État."},
{13,"Population civile","Est civile toute personne qui ne participe pas directement aux hostilités ou qui a cessé d'y participer."},
{14,"Combattant","Est combattante toute personne appartenant à une force armée ou prenant directement part aux hostilités dans les conditions prévues par le présent Code."},
{15,"Territoire","Le territoire d'un État comprend les zones terrestres, installations permanentes et autres espaces reconnus comme relevant de sa souveraineté ou de son administration légale."},
{16,"Document officiel","Est officiel tout acte émis, validé ou enregistré par une autorité compétente dans l'exercice de ses fonctions."},
{17,"Système officiel","Est officiel tout système informatique, terminal, réseau, base de données ou équipement déclaré comme servant à l'exercice d'une fonction publique ou internationale."},
{18,"Bonne foi","Les droits et obligations issus du présent Code doivent être exercés et exécutés de bonne foi."},
{19,"Interdiction de fraude au droit","Nul ne peut invoquer artificiellement une disposition du Code dans le seul but de contourner une autre obligation applicable."},
{20,"Principe de légalité","Aucune responsabilité pénale ou sanction punitive ne peut être fondée sur un comportement qui n'était pas interdit au moment où il a été commis."},
{21,"Hiérarchie des normes","La Charte de l'Union prime le présent Code, lequel prime les règlements d'exécution, décisions administratives et actes internes incompatibles des institutions de l'Union."},
{22,"Traités internationaux","Les traités valablement ratifiés par un État membre l'obligent conformément à leurs termes sous réserve de leur compatibilité avec la Charte et les normes impératives du présent Code."},
{23,"Décisions de la Cour","Les arrêts définitifs de la Cour sont obligatoires pour les parties à l'affaire dans les limites de leur dispositif et de leur compétence."},
{24,"Règlements communs","L'Assemblée peut adopter des règlements d'exécution lorsqu'une disposition de la Charte ou du Code l'y autorise expressément."},
{25,"Droit interne","Un État ne peut invoquer son droit interne pour justifier la non-exécution d'une obligation internationale qu'il a valablement acceptée."},
{26,"Publication obligatoire","Toute norme générale de l'Union doit être publiée au registre officiel avant de pouvoir être opposée aux États ou aux personnes."},
{27,"Date d'entrée en vigueur","Sauf disposition contraire, une norme entre en vigueur vingt-quatre heures après sa publication officielle afin de garantir un délai minimal de connaissance."},
{28,"Non-rétroactivité","Une norme nouvelle ne peut aggraver rétroactivement la situation d'une personne ou d'un État pour des faits antérieurs à son entrée en vigueur."},
{29,"Rétroactivité plus favorable","Une règle pénale ou disciplinaire plus favorable peut s'appliquer aux procédures en cours et aux sanctions non entièrement exécutées."},
{30,"Numérotation permanente","Chaque article reçoit un numéro permanent qui ne peut être réattribué après abrogation afin de préserver l'intégrité des références historiques."},
{31,"Versionnement","Toute modification substantielle d'un article doit créer une nouvelle version datée et conserver l'accès à la version antérieure."},
{32,"Texte consolidé","Le Greffe maintient un texte consolidé indiquant la version actuellement applicable de chaque disposition."},
{33,"Archives juridiques","Les versions anciennes, textes abrogés et historiques de modification sont conservés sans limitation de durée sauf impossibilité matérielle majeure dûment constatée."},
{34,"Interprétation littérale et contextuelle","Le texte d'une disposition s'interprète selon son sens ordinaire, son contexte, son objet et les principes généraux du Code."},
{35,"Interprétation restrictive des sanctions","Les dispositions créant une infraction ou aggravant une sanction sont interprétées strictement et ne peuvent être étendues par analogie défavorable."},
{36,"Interprétation favorable aux droits de la défense","En cas d'ambiguïté durable sur une règle procédurale, l'interprétation qui préserve le mieux l'équité de la procédure doit être privilégiée."},
{37,"Conflit de normes","En cas de conflit entre deux normes de même rang, la norme spéciale prévaut sur la norme générale et la norme postérieure prévaut lorsque les deux ont le même objet."},
{38,"Normes impératives","Aucune convention ne peut autoriser le génocide, l'esclavage, la torture, l'extermination de civils ou tout autre acte déclaré impératif par le présent Code."},
{39,"Langue officielle","La version française constitue le texte de référence du Code tant qu'aucune autre version authentique n'a été adoptée selon la même procédure."},
{40,"Corrections matérielles","Les fautes de frappe, erreurs de renvoi ou défauts purement matériels peuvent être corrigés sans modifier le sens juridique, sous réserve d'un journal public de correction."},
{41,"Droit de demander l'adhésion","Tout État reconnu peut demander à rejoindre l'Union s'il accepte la Charte, le présent Code et la juridiction définie par ceux-ci."},
{42,"Dossier de candidature","La candidature indique au minimum le nom officiel, le gouvernement, les représentants, le territoire revendiqué, les principaux accords existants et les moyens de contact officiels de l'État candidat."},
{43,"Exactitude de la candidature","Toute falsification intentionnelle d'un élément déterminant du dossier de candidature constitue une violation grave susceptible d'entraîner le rejet ou la suspension de l'adhésion."},
{44,"Examen préalable","La candidature fait l'objet d'un examen de conformité portant notamment sur la stabilité de la représentation, l'acceptation des obligations communes et l'absence de fraude manifeste."},
{45,"Audition du candidat","L'État candidat peut être entendu par l'Assemblée afin de répondre aux questions relatives à son adhésion."},
{46,"Vote d'admission","L'admission est prononcée par la majorité qualifiée définie par la Charte ou, à défaut, par les deux tiers des États membres présents et votants."},
{47,"Prise d'effet de l'adhésion","L'adhésion prend effet à l'enregistrement officiel de l'acte de ratification et de la décision d'admission."},
{48,"Identifiant d'État","Chaque État membre reçoit un identifiant permanent de type STATE-XXX destiné aux registres et systèmes informatiques communs."},
{49,"Représentation officielle","Chaque membre désigne au moins un représentant principal et peut désigner des suppléants dont les pouvoirs sont enregistrés."},
{50,"Mise à jour des représentants","Tout changement de représentant ou de gouvernement doit être notifié au Greffe dans les meilleurs délais afin d'éviter les usurpations de pouvoir."},
{51,"Respect du Code","Tout État membre est tenu de respecter et de faire respecter, dans les limites de sa juridiction, les obligations communes qu'il a acceptées."},
{52,"Coopération institutionnelle","Les membres coopèrent avec les institutions de l'Union lorsqu'une demande repose sur une compétence légale et respecte les garanties du présent Code."},
{53,"Coopération judiciaire","Les membres exécutent de bonne foi les demandes judiciaires obligatoires de la Cour, sous réserve des voies de contestation prévues."},
{54,"Conservation des preuves","Dès qu'un État sait ou devrait raisonnablement savoir qu'une procédure est ouverte, il doit empêcher la destruction volontaire des preuves pertinentes placées sous son contrôle."},
{55,"Notification des conflits","Tout membre impliqué dans un conflit armé notifie rapidement à l'Union la nature du conflit, les parties connues et les mesures urgentes prises pour protéger les civils."},
{56,"Déclaration des revendications territoriales","Toute revendication officielle sur un territoire contesté doit être enregistrée afin de permettre l'identification des différends et d'éviter les changements secrets de position."},
{57,"Notification des traités majeurs","Les accords créant des obligations de défense, de frontière, de sanction ou d'intégration durable entre membres doivent être déposés au registre commun."},
{58,"Retrait volontaire","Un État peut se retirer de l'Union par notification écrite conforme à la Charte et après l'expiration du délai de préavis prévu."},
{59,"Effets du retrait","Le retrait n'efface ni les dettes, ni les obligations déjà exigibles, ni la compétence de la Cour sur les faits commis pendant la période d'adhésion."},
{60,"Réadhésion","Un ancien membre peut demander une nouvelle adhésion selon la procédure ordinaire, sous réserve du règlement préalable des obligations demeurées exécutoires."},
{61,"Avertissement institutionnel","L'Assemblée peut adresser un avertissement motivé à un membre qui manque de manière significative à ses obligations sans justifier encore une suspension."},
{62,"Mesures conservatoires institutionnelles","En cas de risque grave et immédiat pour l'Union, certains privilèges institutionnels peuvent être temporairement gelés avant décision définitive, pour la durée strictement nécessaire."},
{63,"Droit d'être entendu","Aucune suspension ou exclusion définitive ne peut être décidée sans avoir offert à l'État concerné une possibilité raisonnable de présenter ses observations."},
{64,"Suspension de certains droits","La suspension peut porter sur le vote, l'accès à certains programmes, la représentation dans certains organes ou d'autres privilèges précisément énumérés dans la décision."},
{65,"Maintien des obligations pendant la suspension","La suspension d'un droit institutionnel ne dispense pas l'État de ses obligations juridiques ni de l'exécution des décisions antérieures."},
{66,"Motifs de suspension","Peuvent notamment justifier une suspension les violations graves et persistantes du Code, le refus durable d'exécuter des arrêts ou la falsification répétée des institutions communes."},
{67,"Durée de suspension","Toute suspension doit être réexaminée périodiquement et ne peut devenir indéfinie sans nouvelle décision motivée."},
{68,"Conditions de réintégration","La décision de suspension énonce, lorsque cela est possible, les mesures dont l'accomplissement permet la réintégration complète du membre."},
{69,"Exclusion de dernier recours","L'exclusion ne peut être prononcée qu'en dernier recours lorsqu'une violation fondamentale et persistante rend manifestement impossible le maintien de l'État au sein de l'Union."},
{70,"Majorité d'exclusion","L'exclusion exige au minimum une majorité des trois quarts des membres présents et votants, sauf règle plus stricte de la Charte."},
{71,"Effets de l'exclusion","L'exclusion met fin aux privilèges de membre mais n'efface pas les obligations nées avant sa prise d'effet ni les réparations dues."},
{72,"Retrait frauduleux","Un retrait demandé dans le seul but d'empêcher l'exécution d'une décision déjà définitive ne prive pas la Cour de sa compétence sur cette décision."},
{73,"Disparition d'un gouvernement","L'absence temporaire de gouvernement fonctionnel ne fait pas disparaître automatiquement l'État ni ses droits essentiels."},
{74,"Gouvernement concurrent","En présence de plusieurs autorités revendiquant la représentation d'un même État, l'Union peut suspendre provisoirement la reconnaissance du représentant jusqu'à décision sur la légitimité procédurale."},
{75,"Succession d'État","En cas de division, fusion ou transformation d'un État, l'Assemblée détermine la continuité des droits et obligations en tenant compte des accords entre les entités concernées."},
{76,"État déplacé","La perte temporaire du contrôle du territoire n'emporte pas nécessairement disparition juridique de l'État lorsqu'un gouvernement et une population demeurent identifiables."},
{77,"État occupé","L'occupation militaire étrangère n'autorise pas l'occupant à se présenter automatiquement comme successeur légal de l'État occupé."},
{78,"Continuité des archives","Les archives officielles d'un État doivent, autant que possible, être préservées lors d'un changement de régime, d'une occupation ou d'une catastrophe."},
{79,"Protection contre l'usurpation","L'utilisation non autorisée du nom, des clés numériques, des sceaux ou des canaux officiels d'un État suspendu ou désorganisé constitue une usurpation institutionnelle."},
{80,"Réexamen exceptionnel","Toute décision d'exclusion, de succession ou de représentation peut être réexaminée si des faits déterminants inconnus au moment de la décision apparaissent ultérieurement."},
{81,"Institutions principales","L'Union comprend au minimum l'Assemblée des États, le Conseil de paix et de sécurité, la Cour internationale de l'Union, le Parquet international, le Greffe et le Secrétariat général."},
{82,"Principe de compétence attribuée","Chaque institution n'exerce que les pouvoirs que lui confèrent la Charte, le présent Code ou un acte adopté sur leur fondement."},
{83,"Séparation des fonctions","Les fonctions législatives, exécutives, d'enquête, d'accusation et de jugement doivent être suffisamment séparées pour garantir l'impartialité et le contrôle mutuel."},
{84,"Assemblée des États","L'Assemblée est l'organe délibérant dans lequel chaque État membre dispose d'une représentation conformément à la Charte."},
{85,"Égalité de représentation","Sauf disposition expresse contraire, chaque État membre dispose d'une voix à l'Assemblée indépendamment de sa puissance, de son territoire ou de ses ressources."},
{86,"Conseil de paix et de sécurité","Le Conseil coordonne la prévention des crises, les cessez-le-feu, les mesures de sécurité collective et le suivi des situations menaçant gravement la paix."},
{87,"Cour internationale de l'Union","La Cour tranche les litiges relevant de sa compétence et juge les infractions internationales selon les procédures prévues par le Code."},
{88,"Parquet international","Le Parquet mène ou dirige les poursuites relevant de la compétence pénale de la Cour et agit indépendamment des gouvernements dans les affaires individuelles."},
{89,"Greffe","Le Greffe conserve les dossiers, authentifie les actes, administre les audiences, maintient les registres et assure la traçabilité des procédures."},
{90,"Secrétariat général","Le Secrétariat assure l'administration générale, la transmission des décisions, la gestion des moyens communs et les fonctions non judiciaires qui lui sont confiées."},
{91,"Services d'enquête","Des enquêteurs peuvent être habilités à recueillir des preuves sous le contrôle du Parquet ou de la Cour et dans les limites fixées par les mandats délivrés."},
{92,"Bureau humanitaire","Un service humanitaire peut coordonner l'aide, l'évacuation de civils, la gestion des personnes déplacées et la protection des convois reconnus."},
{93,"Inspection internationale","Une inspection internationale ne peut être conduite que sur une base légale, un consentement valable ou un mandat judiciaire précisant son objet et son étendue."},
{94,"Budget commun","Les dépenses communes sont décidées et retracées de manière transparente selon les règles budgétaires adoptées par l'Assemblée."},
{95,"Contrôle financier","Les comptes des institutions sont soumis à un contrôle périodique indépendant ou collégial afin de prévenir détournements et conflits d'intérêts."},
{96,"Incompatibilités","Une même personne ne peut exercer simultanément des fonctions dont la réunion créerait un conflit structurel, notamment juger une affaire qu'elle a elle-même poursuivie."},
{97,"Devoir de déclaration","Les responsables des institutions déclarent les intérêts personnels susceptibles d'affecter l'exercice impartial de leurs fonctions."},
{98,"Continuité institutionnelle","Chaque institution prévoit un suppléant, une procédure de remplacement ou une sauvegarde permettant de continuer à fonctionner en cas d'absence, destruction ou perte d'un équipement."},
{99,"Publicité des actes","Les actes normatifs, décisions finales et informations institutionnelles non protégées sont rendus accessibles au public par le registre officiel."},
{100,"Responsabilité des institutions","Une institution de l'Union qui dépasse manifestement ses compétences peut voir son acte annulé ou déclaré inopposable par la Cour selon la procédure de contrôle applicable."},
}
