-- UNS-CIC-500-V1.0 compact seed. {number,title,body}
return {
{101,"Convocation de l'Assemblée","L'Assemblée se réunit selon un calendrier public ou sur convocation extraordinaire lorsqu'une question urgente exige une décision commune."},
{102,"Ordre du jour","L'ordre du jour est communiqué suffisamment tôt pour permettre aux États de préparer leur position, sauf urgence spécialement motivée."},
{103,"Quorum","Aucun vote contraignant ne peut être valablement adopté si moins de la moitié des membres habilités à voter sont représentés, sauf règle plus stricte de la Charte."},
{104,"Majorité simple","La majorité simple correspond à plus de voix favorables que défavorables parmi les suffrages valablement exprimés."},
{105,"Majorité absolue","La majorité absolue correspond à plus de la moitié de l'ensemble des membres habilités à voter."},
{106,"Majorité qualifiée","La majorité qualifiée correspond au seuil spécial prévu par la Charte ou le Code pour les décisions présentant une importance particulière."},
{107,"Abstention","Une abstention n'est ni un vote favorable ni un vote défavorable mais demeure enregistrée dans le procès-verbal."},
{108,"Vote public","Les votes sont publics par principe et le registre mentionne le choix de chaque État, sauf décision exceptionnelle justifiée par la sécurité d'une procédure sensible."},
{109,"Proposition de texte","Tout membre habilité peut déposer une proposition d'article, d'amendement ou de résolution accompagnée d'un objet et d'une justification suffisamment précis."},
{110,"Numéro de proposition","Chaque proposition reçoit un identifiant permanent de type BILL-AAAA-XXXX ou AMEND-AAAA-XXXX afin d'assurer sa traçabilité."},
{111,"Débat","Avant un vote définitif, les membres disposent d'une possibilité raisonnable de discuter du texte et de proposer des modifications."},
{112,"Amendement","Un amendement doit identifier clairement le texte visé, la rédaction proposée et les effets recherchés."},
{113,"Vote article par article","L'Assemblée peut décider de voter séparément plusieurs articles d'un même projet afin d'éviter qu'une disposition contestée n'emporte artificiellement l'ensemble du texte."},
{114,"Adoption finale","Après examen des amendements, le texte consolidé fait l'objet d'un vote final unique sauf procédure spéciale prévue par la Charte."},
{115,"Promulgation","Le texte adopté est authentifié par l'autorité compétente puis transmis au Greffe pour publication et archivage."},
{116,"Registre officiel","Le registre officiel constitue la source publique de référence pour les textes en vigueur, leurs versions, les votes, les décisions et les identifiants institutionnels."},
{117,"Journal des modifications","Toute création, modification, abrogation ou correction d'un texte est inscrite dans un journal horodaté indiquant l'auteur, le motif et la version concernée."},
{118,"Interdiction de falsifier un vote","Altérer intentionnellement un résultat, une liste de votants ou un procès-verbal officiel constitue une violation grave de niveau G4."},
{119,"Corruption législative","Offrir, demander ou accepter un avantage indu en échange d'un vote, d'un retrait de texte ou d'une décision institutionnelle constitue une violation de niveau G4, sans préjudice d'une qualification plus grave."},
{120,"Contrôle de constitutionnalité interne","La Cour peut annuler une norme de l'Union incompatible avec la Charte ou adoptée en violation substantielle de la procédure obligatoire."},
{121,"Compétence contentieuse entre États","La Cour peut trancher un différend entre États lorsqu'ils sont soumis à sa juridiction en vertu de la Charte, du Code, d'un traité ou d'un consentement spécial."},
{122,"Compétence pénale internationale","La Cour peut connaître des infractions individuelles expressément définies par le présent Code lorsque les conditions de compétence sont réunies."},
{123,"Compétence à l'égard des institutions","La Cour peut contrôler la légalité des actes des institutions de l'Union dans les cas prévus par la Charte et le Code."},
{124,"Compétence territoriale","La compétence peut être fondée sur le fait qu'un comportement, un résultat ou une partie substantielle d'une infraction s'est produit sur le territoire d'un État soumis à la Cour."},
{125,"Compétence personnelle","La compétence peut être fondée sur la nationalité, la fonction ou le rattachement juridiquement reconnu de l'auteur ou de la victime lorsque le Code le prévoit."},
{126,"Compétence par consentement","Un État non membre peut accepter la compétence de la Cour pour une affaire, une période ou une catégorie de litiges déterminée."},
{127,"Compétence par traité","Un traité enregistré peut attribuer à la Cour la compétence pour les différends nés de son interprétation ou de son exécution."},
{128,"Compétence temporelle","Sauf règle plus favorable à l'accusé, la Cour ne juge que les faits commis après l'entrée en vigueur de la norme et de la compétence applicables."},
{129,"Continuité de compétence","Le retrait ou la suspension ultérieure d'un État n'efface pas la compétence déjà acquise sur les faits antérieurs."},
{130,"Contestations de compétence","Toute partie peut soulever une exception de compétence avant le jugement au fond ou dès qu'elle découvre le motif invoqué."},
{131,"Pouvoir de statuer sur sa compétence","La Cour décide elle-même, par décision motivée, si les conditions de sa compétence sont réunies."},
{132,"Compétence incidente","Lorsqu'elle est valablement saisie, la Cour peut trancher les questions incidentes indispensables à la résolution de l'affaire."},
{133,"Mesures provisoires","La Cour peut ordonner des mesures provisoires lorsqu'un risque imminent de dommage irréparable exige de préserver des droits avant le jugement final."},
{134,"Limites des mesures provisoires","Une mesure provisoire doit être nécessaire, proportionnée, temporaire et ne pas préjuger définitivement du fond de l'affaire."},
{135,"Avis consultatif","L'Assemblée ou une institution autorisée peut demander un avis consultatif sur une question juridique importante sans qu'il ait automatiquement la force d'un arrêt contentieux."},
{136,"Non bis in idem","Nul ne peut être jugé deux fois par la Cour pour les mêmes faits et sous la même qualification lorsque la première décision est définitive, sauf fraude ayant empêché un véritable jugement."},
{137,"Complémentarité","La Cour peut tenir compte des procédures nationales authentiques et éviter de les remplacer lorsqu'elles sont capables et disposées à traiter effectivement les faits."},
{138,"Défaillance manifeste d'une procédure nationale","Une procédure purement fictive, destinée à soustraire un responsable à toute enquête réelle, peut ne pas faire obstacle à la compétence internationale lorsque le Code l'autorise."},
{139,"Jonction d'affaires","La Cour peut joindre des affaires étroitement liées si cela améliore la cohérence et l'efficacité sans porter atteinte aux droits de la défense."},
{140,"Disjonction","La Cour peut séparer des chefs, parties ou accusés lorsque leur traitement conjoint rendrait la procédure déraisonnablement complexe ou inéquitable."},
{141,"Indépendance des juges","Les juges ne reçoivent aucune instruction d'un gouvernement, d'un militaire, d'une entreprise ou d'une institution quant à l'issue d'une affaire particulière."},
{142,"Serment des juges","Avant d'exercer, chaque juge s'engage publiquement à appliquer le droit avec indépendance, impartialité, diligence et respect des droits de la défense."},
{143,"Impartialité","Un juge doit se récuser lorsqu'un intérêt personnel, une relation étroite ou une participation antérieure raisonnablement susceptible d'affecter son impartialité est établie."},
{144,"Récusation à la demande d'une partie","Une partie peut demander la récusation d'un juge en exposant des faits précis et vérifiables plutôt qu'une simple opposition à ses décisions."},
{145,"Décision sur la récusation","La demande de récusation est tranchée par un juge ou une formation ne comprenant pas la personne dont l'impartialité est contestée."},
{146,"Incompatibilité fonctionnelle","Un juge ne peut juger une affaire dans laquelle il a agi comme procureur, enquêteur, avocat, témoin ou décideur politique directement impliqué."},
{147,"Durée des fonctions","La durée et les modalités de renouvellement des fonctions judiciaires sont fixées par la Charte ou par un statut adopté conformément à celle-ci."},
{148,"Révocation d'un juge","Un juge ne peut être révoqué que pour incapacité durable, violation grave de ses devoirs, corruption ou faute majeure établie selon une procédure contradictoire."},
{149,"Corruption judiciaire","Le fait de promettre, offrir, demander ou accepter un avantage pour influencer un acte judiciaire constitue une infraction de niveau G5 lorsqu'il menace directement l'intégrité d'un procès."},
{150,"Menace contre un juge","Menacer ou exercer une violence sur un juge afin d'influencer, retarder ou empêcher une décision constitue une infraction de niveau G4 ou G5 selon la gravité."},
{151,"Indépendance du Parquet","Le Parquet décide des enquêtes et poursuites sur la base du droit et des preuves, sans recevoir d'ordre politique sur une affaire individuelle."},
{152,"Obligation d'objectivité du Parquet","Le Parquet recherche et communique aussi bien les éléments à charge que les éléments substantiels à décharge dont il a connaissance."},
{153,"Classement motivé","Le Parquet peut classer une affaire lorsqu'il n'existe pas de base suffisante pour poursuivre et doit alors conserver une motivation permettant le contrôle prévu par la procédure."},
{154,"Réouverture d'une enquête","Une enquête classée peut être rouverte sur la base d'éléments nouveaux ou d'une erreur déterminante, sous réserve des règles relatives aux décisions définitives."},
{155,"Greffier","Le Greffier dirige l'administration des dossiers, l'authentification des actes et la conservation des archives sans intervenir dans l'appréciation du fond des affaires."},
{156,"Secret du Greffe","Les agents du Greffe protègent les informations confidentielles auxquelles ils accèdent et ne les utilisent pas à des fins personnelles."},
{157,"Journal d'audit judiciaire","Tout accès sensible, modification, exportation ou suppression autorisée d'un dossier numérique doit laisser une trace horodatée attribuable à un compte ou à une clé identifiée."},
{158,"Sauvegardes judiciaires","Les dossiers essentiels font l'objet de sauvegardes distinctes afin qu'une panne, une destruction de terminal ou un sabotage local ne puisse effacer à lui seul l'historique judiciaire."},
{159,"Continuité de service","En cas d'indisponibilité du système principal, le Greffe applique une procédure de secours permettant d'enregistrer provisoirement les actes puis de les synchroniser sans perte de traçabilité."},
{160,"Responsabilité disciplinaire","Les membres de la Cour, du Parquet et du Greffe peuvent faire l'objet de mesures disciplinaires pour manquement professionnel sans que la discipline puisse servir à punir une décision judiciaire indépendante rendue de bonne foi."},
{161,"Saisine de la Cour","Une affaire est ouverte par une requête, un acte d'accusation, un renvoi autorisé ou tout autre mécanisme expressément prévu par le Code."},
{162,"Numéro de dossier","Chaque affaire reçoit un identifiant permanent de type CASE-AAAA-XXXX qui demeure inchangé jusqu'à l'archivage définitif."},
{163,"Contenu minimal d'une requête","La requête indique les parties, les faits essentiels, les dispositions invoquées, les demandes principales et les éléments disponibles permettant de comprendre le litige."},
{164,"Notification","Toute partie poursuivie ou mise en cause reçoit, dans un délai raisonnable, notification des accusations ou prétentions dirigées contre elle."},
{165,"Délai raisonnable","Les procédures sont conduites sans retard injustifié tout en laissant aux parties le temps nécessaire pour préparer leur dossier."},
{166,"Présomption d'innocence","Toute personne accusée d'une infraction est présumée innocente jusqu'à ce que sa responsabilité soit établie conformément au niveau de preuve requis."},
{167,"Charge de la preuve pénale","Il appartient au Parquet d'établir chaque élément de l'infraction au-delà d'un doute raisonnable."},
{168,"Charge de la preuve civile ou interétatique","Dans les litiges non pénaux, la Cour statue en principe selon la prépondérance des éléments ou tout standard particulier expressément prévu."},
{169,"Droit de connaître les charges","L'accusé doit connaître en temps utile les faits reprochés, leur qualification juridique et les articles invoqués."},
{170,"Droit à l'assistance","Toute personne poursuivie peut être assistée par un conseil, un représentant ou une personne autorisée selon les règles de la Cour."},
{171,"Droit de garder le silence","Nul ne peut être contraint de s'accuser lui-même et le silence d'un accusé ne suffit pas à établir sa culpabilité."},
{172,"Droit de présenter des preuves","Chaque partie peut produire les éléments pertinents et demander l'audition de témoins dans les limites nécessaires à une procédure ordonnée."},
{173,"Droit de contester les preuves","Chaque partie doit pouvoir contester les éléments substantiels invoqués contre elle, sous réserve des mesures de protection légalement justifiées."},
{174,"Audience publique","Les audiences sont publiques par principe, sauf huis clos nécessaire à la protection d'un témoin, d'une information sensible ou du bon déroulement de la justice."},
{175,"Procès-verbal d'audience","Le Greffe établit un relevé suffisamment précis des audiences, décisions incidentes, déclarations et pièces principales."},
{176,"Défaut d'une partie","L'absence d'une partie régulièrement convoquée n'autorise une décision en son absence que si ses droits ont été protégés et si la procédure applicable le permet."},
{177,"Interprétation et compréhension","La Cour veille à ce qu'une partie comprenne réellement la procédure et les actes qui lui sont opposés, notamment lorsque des termes techniques ou plusieurs langues sont utilisés."},
{178,"Respect et ordre de l'audience","Le juge peut prendre les mesures proportionnées nécessaires pour empêcher insultes, interruptions, menaces, destruction de preuve ou obstruction pendant l'audience."},
{179,"Accords procéduraux","Les parties peuvent convenir de points de procédure ou de faits non contestés si cet accord ne prive pas la Cour de vérifier les éléments indispensables à la légalité de sa décision."},
{180,"Clôture des débats","Avant le délibéré, chaque partie dispose d'une possibilité finale et raisonnable de présenter ses conclusions sur les faits, le droit et les sanctions demandées."},
{181,"Ouverture d'une enquête","Une enquête peut être ouverte lorsqu'il existe des informations suffisamment crédibles laissant supposer qu'une violation relevant de la compétence de la Cour a pu être commise."},
{182,"Proportionnalité de l'enquête","Les actes d'enquête doivent être adaptés à la gravité des faits et éviter les intrusions inutiles dans les droits des personnes ou des États."},
{183,"Mandat judiciaire","Une perquisition, saisie intrusive, interception ciblée ou accès forcé à un système protégé exige un mandat lorsque le Code ne prévoit pas une autre base légale urgente."},
{184,"Contenu du mandat","Le mandat identifie l'autorité exécutante, l'objet recherché, le lieu ou système visé, la durée et les limites nécessaires à son exécution."},
{185,"Urgence","En cas de risque imminent de disparition d'une preuve ou de danger grave pour des personnes, une mesure conservatoire limitée peut être prise avant validation judiciaire rapide."},
{186,"Chaîne de conservation","Toute preuve matérielle ou numérique importante doit être accompagnée d'un historique indiquant sa collecte, ses détenteurs successifs, ses copies et les opérations susceptibles de l'avoir modifiée."},
{187,"Authenticité","Une preuve doit être suffisamment authentifiée pour permettre à la Cour de déterminer qu'elle correspond raisonnablement à ce qu'elle prétend représenter."},
{188,"Intégrité numérique","Les fichiers, journaux et messages numériques sont conservés avec leurs métadonnées utiles et, lorsque possible, une empreinte de vérification permettant de détecter les modifications ultérieures."},
{189,"Admissibilité","La Cour peut exclure une preuve non pertinente, manifestement peu fiable, obtenue par une violation grave ou dont l'effet préjudiciable excède largement la valeur probante."},
{190,"Preuve obtenue illégalement","L'illégalité d'une collecte n'entraîne pas automatiquement l'exclusion mais la Cour apprécie la gravité de la violation, son effet sur la fiabilité et l'équité globale de la procédure."},
{191,"Torture et preuve","Aucune déclaration obtenue par torture ne peut être utilisée pour établir la culpabilité de la personne torturée, sauf pour prouver l'existence de la torture elle-même."},
{192,"Témoins","Toute personne appelée comme témoin doit dire la vérité dans les limites de ce qu'elle sait personnellement et peut signaler lorsqu'elle n'est pas certaine d'un fait."},
{193,"Faux témoignage","Mentir volontairement sur un fait déterminant après avoir accepté l'obligation de vérité constitue une infraction de niveau G3 ou G4 selon les conséquences."},
{194,"Subornation de témoin","Offrir un avantage, menacer ou faire pression sur un témoin afin de modifier son témoignage constitue une infraction de niveau G4."},
{195,"Protection des témoins","La Cour peut protéger l'identité, la localisation ou les modalités d'audition d'un témoin lorsqu'un risque sérieux est établi, tout en préservant les droits essentiels de la défense."},
{196,"Experts","La Cour peut entendre un expert sur une question technique à condition que sa compétence, ses méthodes et ses éventuels conflits d'intérêts soient déclarés."},
{197,"Inspection de lieux","Une inspection peut être ordonnée lorsque l'état d'un lieu, d'une installation ou d'un système présente une utilité directe pour la manifestation de la vérité."},
{198,"Destruction de preuve","Détruire, altérer ou dissimuler sciemment une preuve importante après connaissance d'une enquête constitue une infraction distincte de niveau G4."},
{199,"Fabrication de preuve","Créer, falsifier ou modifier délibérément un élément destiné à tromper la Cour constitue une infraction de niveau G4 ou G5 si elle provoque une condamnation injuste."},
{200,"Archivage des pièces","Les pièces versées au dossier sont indexées, numérotées et conservées de manière à permettre leur consultation, leur vérification et leur restitution éventuelle."},
}
