-- UNS-CIC-500-V1.0 compact seed. {number,title,body}
return {
{201,"Motivation des décisions","Toute décision au fond expose les faits retenus, les preuves essentielles, les règles appliquées, le raisonnement juridique et le dispositif prononcé."},
{202,"Identification des articles","Tout jugement mentionne les numéros et versions des articles appliqués afin de permettre une vérification ultérieure exacte."},
{203,"Individualisation de la sanction","La sanction tient compte de la gravité, de l'intention, du rôle concret, du dommage, de la récidive, de la coopération et des réparations déjà accomplies."},
{204,"Proportionnalité","Aucune sanction ne doit excéder ce qui est raisonnablement nécessaire pour punir, réparer, prévenir la répétition et protéger l'ordre commun."},
{205,"Circonstances aggravantes","Peuvent aggraver une sanction la préméditation, l'abus d'autorité, la vulnérabilité des victimes, la récidive, l'ampleur du dommage ou la dissimulation organisée."},
{206,"Circonstances atténuantes","Peuvent atténuer une sanction la coopération substantielle, la reconnaissance sincère des faits, la réparation spontanée, la contrainte ou un rôle secondaire établi."},
{207,"Avertissement officiel","Pour les manquements mineurs, la Cour peut prononcer un avertissement officiel assorti d'obligations de mise en conformité."},
{208,"Ordre de cessation","La Cour peut ordonner la cessation immédiate ou progressive d'un comportement déclaré illégal lorsque celui-ci se poursuit."},
{209,"Restitution","La restitution vise à rétablir, autant que possible, la situation existant avant la violation, notamment par retour de biens, ressources, documents ou territoires."},
{210,"Indemnisation","Lorsque la restitution est impossible ou insuffisante, une indemnisation proportionnée au dommage matériel établi peut être ordonnée."},
{211,"Réparation symbolique","La Cour peut ordonner une reconnaissance officielle, une rectification publique, des excuses institutionnelles ou une autre mesure symbolique lorsque cela contribue à réparer un préjudice non matériel."},
{212,"Amende","Une amende doit être déterminée en tenant compte de la gravité des faits et des ressources du condamné afin d'éviter qu'elle soit dérisoire ou manifestement excessive."},
{213,"Suspension de droits institutionnels","La Cour ou l'organe compétent peut suspendre certains droits liés à l'Union lorsque cette mesure est autorisée et directement liée à la violation constatée."},
{214,"Confiscation ciblée","Les biens directement issus d'une infraction ou principalement utilisés pour la commettre peuvent être confisqués sur décision motivée, sous réserve des droits des tiers de bonne foi."},
{215,"Interdiction professionnelle","Une personne condamnée pour abus grave de fonction peut être temporairement interdite d'exercer une fonction internationale ou une fonction publique déterminée."},
{216,"Appel","Une partie peut interjeter appel dans les cas prévus pour erreur de droit, erreur déterminante de fait, vice procédural grave ou sanction manifestement disproportionnée."},
{217,"Délai d'appel","Le délai d'appel court à compter de la notification du jugement et doit être suffisamment long pour permettre la préparation d'un recours effectif."},
{218,"Effet de l'appel","L'appel suspend l'exécution des sanctions irréversibles, sauf mesure provisoire spécialement justifiée par un danger immédiat."},
{219,"Révision","Une décision définitive peut exceptionnellement être révisée lorsqu'une preuve nouvelle décisive apparaît ou qu'une fraude majeure ayant affecté le jugement est démontrée."},
{220,"Exécution des décisions","Les États membres et institutions compétentes prennent les mesures nécessaires pour exécuter de bonne foi les décisions définitives relevant de leur juridiction."},
{221,"Fait internationalement illicite","Un État engage sa responsabilité lorsqu'un comportement qui lui est attribuable viole une obligation internationale qui lui est applicable."},
{222,"Attribution aux organes de l'État","Le comportement d'un organe officiel est attribuable à l'État lorsqu'il agit dans l'exercice ou sous l'apparence de ses fonctions, même s'il dépasse certaines instructions internes."},
{223,"Agents habilités","Le comportement d'une personne ou entité spécialement habilitée à exercer une prérogative publique peut être attribué à l'État pour les actes accomplis dans cette mission."},
{224,"Contrôle d'un groupe","Les actes d'un groupe non officiel peuvent être attribués à un État lorsqu'il est établi que celui-ci a dirigé ou contrôlé de manière déterminante l'opération concernée."},
{225,"Adoption d'un acte","Un État peut engager sa responsabilité lorsqu'il reconnaît et adopte expressément comme sien un comportement initialement commis par une autre entité."},
{226,"Aide à une violation","Un État qui aide sciemment un autre État à commettre une violation engage sa responsabilité si son assistance contribue substantiellement à l'acte illicite."},
{227,"Direction ou contrainte d'un autre État","Un État qui dirige ou contraint un autre État à commettre une violation peut engager une responsabilité propre distincte de celle de l'exécutant."},
{228,"Force majeure","Un événement irrésistible et extérieur rendant matériellement impossible l'exécution peut exclure temporairement l'illicéité dans les limites strictes de cet empêchement."},
{229,"Détresse","Un agent peut être excusé d'un manquement limité lorsqu'il n'existait aucun autre moyen raisonnable de sauver des vies placées sous sa responsabilité et que la situation n'a pas été volontairement créée."},
{230,"État de nécessité","La nécessité ne peut être invoquée qu'exceptionnellement pour protéger un intérêt essentiel contre un péril grave et imminent sans sacrifier de manière comparable un intérêt essentiel d'autrui."},
{231,"Légitime défense comme circonstance","Une mesure conforme aux règles de légitime défense n'est pas illicite du seul fait qu'elle affecte l'État agresseur, sous réserve du respect des autres obligations applicables."},
{232,"Cessation","L'État responsable doit mettre fin au comportement illicite lorsqu'il se poursuit."},
{233,"Garanties de non-répétition","La Cour peut ordonner des mesures raisonnables visant à prévenir une répétition lorsqu'un risque sérieux de récidive est établi."},
{234,"Réparation intégrale","L'État responsable doit réparer les conséquences directes et suffisamment établies de sa violation dans la mesure raisonnablement possible."},
{235,"Restitution territoriale ou matérielle","Lorsqu'un bien ou territoire a été illégalement pris, la restitution constitue la réparation privilégiée si elle est matériellement possible et ne crée pas une charge manifestement disproportionnée."},
{236,"Compensation","La compensation couvre les pertes établies qui ne peuvent être réparées par restitution, sans conduire à un enrichissement injustifié."},
{237,"Satisfaction","Une constatation officielle de violation, une reconnaissance publique ou une autre mesure non financière peut réparer une atteinte à la dignité ou à la souveraineté."},
{238,"Contribution au dommage","La réparation peut être réduite lorsque la victime a contribué de manière déterminante et fautive au dommage, sans effacer la violation initiale."},
{239,"Obligation de limiter le dommage","La victime doit prendre les mesures raisonnables dont elle dispose pour éviter l'aggravation artificielle d'un dommage déjà survenu."},
{240,"Exécution échelonnée","Lorsque l'exécution immédiate d'une réparation est matériellement impossible, la Cour peut approuver un calendrier vérifiable sans supprimer l'obligation principale."},
{241,"Règlement pacifique des différends","Les États règlent prioritairement leurs différends par négociation, médiation, arbitrage, enquête, conciliation ou voie judiciaire."},
{242,"Interdiction de l'agression","Le recours à la force armée contre l'intégrité territoriale ou l'indépendance politique d'un autre État est interdit sauf fondement expressément reconnu par le présent Code."},
{243,"Menace illicite de force","La menace crédible d'employer une force qui serait elle-même illicite constitue une violation distincte lorsqu'elle vise à contraindre un autre État."},
{244,"Légitime défense individuelle","Un État victime d'une attaque armée peut employer la force nécessaire et proportionnée pour repousser l'attaque et prévenir sa poursuite immédiate."},
{245,"Légitime défense collective","Des États peuvent assister un État victime d'une attaque armée à sa demande, dans les mêmes limites de nécessité et de proportionnalité."},
{246,"Notification de légitime défense","Un État invoquant la légitime défense informe rapidement le Conseil de paix et de sécurité des faits, objectifs et principales mesures militaires prises."},
{247,"Fin de la légitime défense","La justification de légitime défense cesse lorsque l'attaque et le danger immédiat cessent ou lorsqu'une solution collective effective remplace l'action unilatérale."},
{248,"Consentement à une présence militaire","La présence de forces étrangères peut être fondée sur le consentement clair d'un gouvernement compétent, dans les limites de la mission acceptée."},
{249,"Retrait du consentement","Un État peut retirer un consentement militaire selon les termes de l'accord applicable, après quoi les forces étrangères doivent organiser leur retrait dans un délai raisonnable."},
{250,"Opérations de sécurité collective","L'Union peut autoriser des opérations communes lorsque la Charte le permet et qu'une menace grave à la paix ne peut être traitée par des moyens moins coercitifs."},
{251,"Mandat des opérations communes","Toute opération commune dispose d'un mandat écrit précisant objectif, zone, durée, commandement, règles essentielles et mécanismes de contrôle."},
{252,"Cessez-le-feu","Un cessez-le-feu accepté lie les parties selon ses termes et toute violation intentionnelle substantielle constitue une violation internationale."},
{253,"Armistice","Un armistice suspend les hostilités selon les conditions convenues sans régler automatiquement les questions politiques ou territoriales du conflit."},
{254,"Faux prétexte de guerre","Fabriquer sciemment un incident, une attaque ou une preuve afin de créer un prétexte artificiel à une guerre constitue une violation de niveau G5."},
{255,"Attaque sous fausse attribution","Organiser une attaque destinée à faire accuser un État tiers afin de provoquer un conflit constitue une violation de niveau G5."},
{256,"Blocus","Un blocus n'est licite que s'il repose sur une base juridique reconnue, respecte les règles humanitaires et n'a pas pour objet principal d'affamer la population civile."},
{257,"Zone démilitarisée","Une zone démilitarisée créée par accord ou décision valide doit être respectée par toutes les parties et clairement enregistrée."},
{258,"Observateurs internationaux","Des observateurs neutres peuvent être déployés avec le consentement requis ou sur une autre base légale afin de vérifier un cessez-le-feu ou une situation de sécurité."},
{259,"Incidents frontaliers","Un incident localisé ne doit pas être présenté comme une autorisation automatique d'escalade générale lorsque des moyens raisonnables de vérification et de désescalade existent."},
{260,"Obligation de désescalade","Les parties à une crise prennent, lorsque cela est raisonnablement possible, des mesures de communication, identification et séparation des forces afin de réduire le risque d'affrontement accidentel."},
{261,"Distinction","Les parties distinguent en permanence les objectifs militaires des personnes et biens civils et ne dirigent leurs attaques que contre des objectifs militaires licites."},
{262,"Proportionnalité des attaques","Une attaque est interdite lorsque les dommages civils prévisibles seraient manifestement excessifs par rapport à l'avantage militaire concret et direct attendu."},
{263,"Précautions","Les parties prennent toutes les précautions raisonnablement possibles pour vérifier les cibles, choisir les moyens et réduire les dommages civils."},
{264,"Avertissement","Lorsqu'une attaque risque d'affecter significativement des civils, un avertissement effectif est donné lorsque les circonstances le permettent sans compromettre de manière décisive l'opération."},
{265,"Interdiction des attaques indiscriminées","Les attaques qui ne peuvent être dirigées contre un objectif militaire déterminé ou dont les effets ne peuvent être raisonnablement limités sont interdites."},
{266,"Objectifs militaires","Un bien n'est un objectif militaire que si sa nature, son emplacement, son usage ou sa destination apporte une contribution effective à l'action militaire et si sa neutralisation procure un avantage militaire défini."},
{267,"Protection des biens civils","Les habitations, commerces, écoles, lieux culturels et autres biens civils ne peuvent être attaqués sauf s'ils deviennent temporairement des objectifs militaires."},
{268,"Protection des hôpitaux","Les hôpitaux, postes médicaux, ambulances et personnels sanitaires bénéficient d'une protection spéciale tant qu'ils ne sont pas utilisés pour commettre des actes nuisibles à l'ennemi en dehors de leur fonction humanitaire."},
{269,"Protection des lieux de culte","Les lieux de culte et monuments culturels sont protégés contre les attaques et l'utilisation militaire abusive, sauf perte de protection dans les conditions strictes du Code."},
{270,"Personnel humanitaire","Le personnel humanitaire impartial et identifiable doit pouvoir accomplir sa mission et ne doit pas être pris pour cible."},
{271,"Civils prenant directement part aux hostilités","Un civil perd temporairement la protection contre l'attaque pendant la durée de sa participation directe aux hostilités, sans perdre ses autres garanties fondamentales."},
{272,"Personnes hors de combat","Une personne blessée, capturée, inconsciente, désarmée ou manifestement rendue hors de combat ne peut être attaquée intentionnellement."},
{273,"Reddition","Il est interdit de tuer ou blesser un adversaire qui manifeste clairement son intention de se rendre et qui ne commet plus d'acte hostile."},
{274,"Perfide utilisation d'une protection","Il est interdit de feindre frauduleusement un statut protégé, une reddition ou une mission humanitaire afin de tuer, blesser ou capturer l'adversaire."},
{275,"Uniformes et signes adverses","L'usage des insignes, uniformes ou identifiants de l'adversaire est interdit pendant une attaque lorsqu'il vise à tromper sur l'identité du combattant."},
{276,"Boucliers humains","Utiliser la présence ou le déplacement de civils afin de protéger un objectif militaire contre une attaque constitue une violation grave de niveau G5."},
{277,"Famine comme méthode de guerre","Il est interdit d'utiliser intentionnellement la privation de nourriture, d'eau ou de biens indispensables à la survie des civils comme méthode de guerre."},
{278,"Pillage","L'appropriation privée ou organisée de biens civils sans nécessité militaire légale ni procédure régulière constitue un pillage interdit de niveau G3 à G5 selon son ampleur."},
{279,"Destruction sans nécessité","Détruire largement des biens sans nécessité militaire impérieuse et de manière disproportionnée constitue une violation grave."},
{280,"Obligation après les combats","Après les combats, les parties prennent les mesures raisonnables pour rechercher les blessés, sécuriser les dangers immédiats et faciliter l'évacuation des civils lorsque possible."},
{281,"Responsabilité pénale individuelle","Toute personne qui commet, ordonne, planifie, facilite ou contribue intentionnellement à une infraction internationale engage sa responsabilité selon son rôle réel."},
{282,"Tentative","La tentative est punissable lorsqu'un commencement d'exécution non équivoque est établi et que l'infraction n'a échoué que pour une cause indépendante de la volonté de l'auteur."},
{283,"Complicité","Aider sciemment à la commission d'une infraction par une contribution substantielle constitue une complicité."},
{284,"Ordre supérieur","Le fait d'avoir reçu un ordre n'exonère pas automatiquement l'auteur lorsqu'il savait que l'ordre était manifestement illégal ou lorsqu'il disposait d'une possibilité raisonnable de refuser."},
{285,"Responsabilité du commandement","Un supérieur peut être responsable s'il savait ou aurait dû savoir que ses subordonnés commettaient des crimes graves et n'a pas pris les mesures raisonnables pour les prévenir ou les réprimer."},
{286,"Génocide","Commettre certains actes graves avec l'intention de détruire, en tout ou en partie, un groupe national, ethnique, racial ou religieux protégé constitue un crime international de niveau G5."},
{287,"Meurtre de masse de civils","Le meurtre intentionnel et généralisé ou systématique de civils constitue un crime international majeur de niveau G5."},
{288,"Extermination","Imposer intentionnellement des conditions de vie destinées à provoquer la destruction massive d'une population civile constitue un crime de niveau G5."},
{289,"Déportation forcée","Déplacer massivement une population civile par force ou menace sans motif légal reconnu constitue une violation de niveau G5 lorsqu'elle est généralisée ou systématique."},
{290,"Emprisonnement arbitraire généralisé","La privation grave de liberté de nombreuses personnes en violation fondamentale des garanties judiciaires peut constituer un crime international majeur lorsqu'elle s'inscrit dans une politique généralisée ou systématique."},
{291,"Torture","Infliger intentionnellement une douleur ou souffrance grave à une personne sous contrôle afin d'obtenir une information, punir, intimider ou discriminer constitue une infraction de niveau G5."},
{292,"Violences sexuelles en conflit","Les violences sexuelles imposées par force, menace, coercition ou abus de contrôle constituent des crimes graves, avec une qualification aggravée lorsqu'elles sont généralisées, systématiques ou liées à un conflit."},
{293,"Persécution","Priver intentionnellement et gravement un groupe de droits fondamentaux pour des motifs discriminatoires peut constituer un crime majeur lorsqu'il s'inscrit dans une attaque généralisée ou systématique."},
{294,"Disparition forcée","L'arrestation ou enlèvement suivi d'un refus organisé de reconnaître le sort ou le lieu de détention d'une personne constitue une violation grave et peut relever du niveau G5 lorsqu'il est systématique."},
{295,"Prise d'otages","Détenir une personne et menacer de lui nuire afin de contraindre un tiers à agir ou s'abstenir constitue une infraction grave de niveau G4 ou G5."},
{296,"Exécution sommaire","Tuer intentionnellement une personne détenue, désarmée ou hors de combat sans nécessité immédiate de défense constitue une infraction de niveau G5."},
{297,"Attaque intentionnelle contre des civils","Diriger sciemment une attaque contre une population civile ou des civils ne participant pas directement aux hostilités constitue une infraction de niveau G5."},
{298,"Attaque contre une mission humanitaire","Diriger intentionnellement une attaque contre une mission humanitaire protégée et identifiable constitue une infraction de niveau G5 sauf perte de protection légalement établie."},
{299,"Destruction de preuves de crimes majeurs","Organiser la destruction, falsification ou dissimulation de preuves afin d'empêcher l'enquête sur un crime international majeur constitue une infraction autonome de niveau G4 ou G5."},
{300,"Imprescriptibilité des crimes les plus graves","Les crimes de niveau G5 expressément qualifiés de crimes internationaux majeurs ne sont pas soumis à un délai d'extinction des poursuites dans le système de l'Union."},
}
