-- UNS-CIC-500-V1.0 compact seed. {number,title,body}
return {
{301,"Dignité humaine","Toute personne relevant de la juridiction d'un membre doit être traitée avec un minimum de dignité, y compris en période de crise ou de conflit."},
{302,"Droit à la vie","Nul ne peut être privé arbitrairement de la vie et tout usage de force potentiellement létale doit répondre à une nécessité réelle et être proportionné à la menace."},
{303,"Interdiction de la torture","La torture et les traitements cruels, inhumains ou dégradants sont interdits sans exception fondée sur la guerre, l'urgence ou un ordre supérieur."},
{304,"Interdiction de l'esclavage","L'esclavage, la traite de personnes et le travail imposé sous menace grave hors des cas strictement prévus par la loi sont interdits."},
{305,"Égalité juridique","Les garanties fondamentales du présent Livre s'appliquent sans discrimination arbitraire fondée notamment sur l'origine, la nationalité, le sexe, la langue, la religion ou l'appartenance politique supposée."},
{306,"Liberté individuelle","Nul ne peut être arrêté ou détenu sans base légale identifiable ni pour une durée supérieure à ce que justifie cette base."},
{307,"Information du détenu","Toute personne arrêtée est informée dès que possible des motifs essentiels de sa privation de liberté et de l'autorité qui l'ordonne."},
{308,"Registre de détention","Toute détention officielle est enregistrée avec l'identité de la personne, le motif, le lieu, l'heure d'entrée, les transferts et la décision de libération."},
{309,"Contrôle de la détention","Toute personne détenue peut demander qu'une autorité compétente examine dans un délai raisonnable la légalité du maintien en détention."},
{310,"Conditions de détention","Les personnes détenues disposent au minimum d'eau, de nourriture, d'un abri raisonnable, de soins urgents et d'une protection contre les violences arbitraires."},
{311,"Séparation des catégories","Lorsque les moyens le permettent, les civils, prisonniers de guerre, condamnés et personnes en attente de jugement sont séparés selon leur statut et leurs besoins de sécurité."},
{312,"Soins aux détenus","Un détenu malade ou blessé reçoit les soins raisonnablement disponibles sans discrimination fondée sur son camp ou son statut."},
{313,"Contacts et information","Sous réserve de nécessités de sécurité précises, un détenu peut faire connaître son lieu de détention et sa situation à un proche, un représentant ou une autorité compétente."},
{314,"Interrogatoire","Un interrogatoire ne peut reposer sur la torture, la menace illégale, la privation extrême ou tout procédé détruisant volontairement la capacité de consentement de la personne."},
{315,"Mineurs","Lorsqu'une personne mineure est impliquée, son âge et sa vulnérabilité doivent être pris en compte dans les mesures de détention, de jugement et de protection."},
{316,"Liberté de conscience","Nul ne peut être forcé d'adopter, d'abandonner ou de simuler une conviction religieuse ou philosophique sous peine, menace ou violence publique."},
{317,"Expression et information","La liberté d'expression et d'information est protégée, sous réserve des restrictions légales strictement nécessaires à la protection d'autrui, d'une procédure judiciaire ou d'un secret légitime."},
{318,"Réunion pacifique","Les réunions pacifiques ne peuvent être interdites arbitrairement et les restrictions doivent reposer sur un risque réel et proportionné."},
{319,"Propriété","Nul ne peut être privé arbitrairement de ses biens; toute saisie publique définitive doit reposer sur une base légale, une procédure traçable et, lorsqu'il y a lieu, une compensation."},
{320,"Recours effectif","Toute personne victime d'une violation grave imputable à une autorité doit disposer d'un mécanisme permettant d'en demander l'examen et, lorsque la violation est établie, une réparation appropriée."},
{321,"Relations diplomatiques","Les États sont libres d'établir, limiter ou rompre des relations diplomatiques sans que la rupture constitue à elle seule une déclaration de guerre."},
{322,"Reconnaissance des représentants","Un représentant diplomatique n'agit au nom d'un État qu'après notification ou accréditation selon la procédure reconnue par l'État d'accueil ou l'Union."},
{323,"Protection des missions","Les locaux officiellement reconnus comme mission diplomatique bénéficient d'une protection particulière contre les intrusions arbitraires."},
{324,"Limites de l'inviolabilité","La protection d'une mission ne peut être utilisée comme couverture pour des actes de violence immédiate, une détention secrète illégale ou une attaque armée contre l'État d'accueil."},
{325,"Courrier diplomatique","Les communications officiellement identifiées comme diplomatiques bénéficient d'une protection contre l'ouverture arbitraire, sous réserve des procédures exceptionnelles prévues en cas de danger grave et démontrable."},
{326,"Immunité fonctionnelle","Un représentant bénéficie, dans les limites prévues par les accords applicables, d'une protection pour les actes accomplis officiellement afin de permettre l'exercice indépendant de sa mission."},
{327,"Abus d'immunité","L'immunité ne transforme pas un acte interdit en acte licite et peut être levée ou limitée selon la procédure applicable."},
{328,"Persona non grata","Un État d'accueil peut demander le rappel d'un représentant étranger sans être tenu de poursuivre celui-ci, sous réserve des autres obligations applicables."},
{329,"Négociation","Les négociations internationales doivent être conduites de bonne foi et les déclarations présentées comme officielles engagent leur auteur dans les limites de son pouvoir déclaré."},
{330,"Conclusion des traités","Un traité est conclu par des représentants habilités puis ratifié ou approuvé selon les procédures de chaque partie lorsque cette étape est requise."},
{331,"Consentement libre","Un traité obtenu par menace illégale, violence ou falsification déterminante du consentement peut être déclaré invalide."},
{332,"Fraude dans un traité","La dissimulation volontaire d'un fait essentiel destinée à obtenir la signature d'un accord peut justifier une contestation de validité lorsque la fraude a été déterminante."},
{333,"Erreur essentielle","Une erreur portant sur un fait ou une situation constituant une base essentielle du consentement peut être invoquée si la partie qui s'en prévaut n'a pas elle-même provoqué l'erreur par négligence grave."},
{334,"Exécution de bonne foi","Tout traité en vigueur lie ses parties et doit être exécuté de bonne foi conformément à son texte et à son objet."},
{335,"Enregistrement des traités","Les traités entre membres portant sur la paix, les frontières, la défense, les sanctions ou la coopération institutionnelle sont déposés au registre commun."},
{336,"Amendement d'un traité","Un traité peut être amendé selon la procédure qu'il prévoit ou, à défaut, par l'accord des parties affectées."},
{337,"Suspension d'un traité","Une violation substantielle peut justifier la suspension d'un traité dans les conditions prévues par celui-ci ou par les règles générales, sans autoriser une réaction disproportionnée."},
{338,"Extinction d'un traité","Un traité peut prendre fin par accord, échéance, réalisation de son objet, dénonciation prévue ou autre cause légalement reconnue."},
{339,"Changement fondamental de circonstances","Un changement imprévisible ne peut justifier la fin d'un traité que s'il transforme radicalement une obligation essentielle et ne résulte pas de la violation de la partie qui l'invoque."},
{340,"Règlement des différends diplomatiques","Les États privilégient les canaux diplomatiques, la médiation et les mécanismes convenus avant de recourir à des mesures coercitives non urgentes."},
{341,"Intégrité territoriale","Le territoire reconnu d'un État ne peut être acquis par une agression ou une menace illicite de force."},
{342,"Délimitation des frontières","Les frontières résultent des accords, décisions, cartes reconnues, pratiques établies et autres éléments de preuve appréciés ensemble lorsqu'un différend existe."},
{343,"Bornage et signalisation","Les États voisins peuvent matérialiser leurs frontières par bornes, panneaux ou coordonnées enregistrées sans modifier unilatéralement la ligne juridique convenue."},
{344,"Incident de frontière","Une violation ponctuelle de frontière doit faire l'objet d'une vérification avant toute escalade et, lorsqu'elle est accidentelle, d'une procédure de retour et d'enquête."},
{345,"Franchissement autorisé","Les États peuvent établir des points de passage, permis, couloirs ou procédures de contrôle compatibles avec les obligations humanitaires applicables."},
{346,"Fermeture de frontière","La fermeture temporaire d'une frontière est possible pour motif de sécurité, de santé ou de crise à condition de rester proportionnée et de prévoir les exceptions humanitaires nécessaires."},
{347,"Territoire contesté","L'existence d'une revendication concurrente n'autorise aucune partie à modifier par la force le statut du territoire avant règlement du différend."},
{348,"Administration provisoire","Les parties peuvent convenir d'une administration provisoire d'un territoire sans préjuger du titre souverain définitif."},
{349,"Occupation militaire","Un territoire est occupé lorsqu'il est placé de fait sous l'autorité d'une force étrangère capable d'y exercer un contrôle effectif contre la volonté de l'État souverain."},
{350,"Caractère temporaire de l'occupation","L'occupation n'emporte pas transfert automatique de souveraineté et l'occupant administre le territoire sous les limites du présent Code."},
{351,"Protection de la population occupée","L'occupant doit maintenir l'ordre et les services essentiels raisonnablement possibles tout en protégeant la population contre les violences et représailles arbitraires."},
{352,"Droit local sous occupation","Les règles locales demeurent applicables autant que possible sauf lorsqu'elles empêchent l'occupant de remplir ses obligations de sécurité ou contredisent les garanties impératives."},
{353,"Réquisitions sous occupation","Les réquisitions doivent répondre à un besoin réel, être proportionnées, enregistrées et ne pas priver la population des biens indispensables à sa survie."},
{354,"Transfert forcé de population","Il est interdit de déplacer de force la population d'un territoire occupé sauf évacuation temporaire strictement nécessaire à sa sécurité ou à une nécessité militaire impérative."},
{355,"Colonisation forcée","L'installation organisée de populations dans un territoire occupé afin d'en modifier durablement la composition et le statut est interdite."},
{356,"Annexion forcée","Une annexion obtenue par agression, occupation illicite ou contrainte militaire n'est pas reconnue par l'Union."},
{357,"Sécession et autodétermination","Toute revendication d'indépendance est examinée selon les faits, les accords applicables, la volonté de la population concernée et le respect des droits fondamentaux sans présumer automatiquement de son issue."},
{358,"Référendum territorial","Un référendum territorial n'a de valeur internationale que s'il est organisé sans coercition déterminante, avec un corps électoral identifiable et des garanties raisonnables de sincérité."},
{359,"Ressources des territoires contestés","L'exploitation massive ou irréversible des ressources d'un territoire contesté doit être évitée lorsqu'elle préjuge du règlement ou prive durablement l'autre partie de ses droits possibles."},
{360,"Restitution après occupation","À la fin d'une occupation, les archives, biens publics et infrastructures saisis doivent être restitués ou transférés selon un inventaire vérifiable, sauf accord contraire valable."},
{361,"Liberté des échanges licites","Les États peuvent commercer librement sous réserve des embargos, contrôles et restrictions légalement adoptés."},
{362,"Non-discrimination commerciale arbitraire","Les avantages ou restrictions commerciales entre membres doivent reposer sur un accord, une politique publique identifiable ou une mesure de sécurité plutôt que sur une discrimination dépourvue de justification."},
{363,"Contrats internationaux","Les contrats conclus entre États, entreprises ou institutions doivent être exécutés de bonne foi selon la loi ou les règles choisies par les parties."},
{364,"Fraude commerciale","La tromperie intentionnelle portant sur la nature, la quantité, l'origine ou la propriété d'un bien dans le but d'obtenir un avantage substantiel constitue une infraction de niveau G2 à G4."},
{365,"Contrefaçon de documents financiers","Fabriquer ou altérer un document bancaire, une preuve de paiement ou un titre afin de tromper un tiers constitue une infraction de niveau G3 ou G4."},
{366,"Détournement de fonds publics","S'approprier ou faire utiliser à des fins personnelles des fonds publics confiés en raison d'une fonction constitue une infraction de niveau G3 à G5 selon le montant et les conséquences."},
{367,"Blanchiment","Dissimuler sciemment l'origine criminelle de biens ou fonds par des opérations destinées à leur donner une apparence licite constitue une infraction de niveau G3 ou G4."},
{368,"Corruption active","Offrir ou promettre un avantage indu afin qu'un agent public accomplisse ou omette un acte de sa fonction constitue une infraction de niveau G3 ou G4."},
{369,"Corruption passive","Demander, accepter ou recevoir un avantage indu en échange d'un acte ou d'une abstention liée à une fonction publique constitue une infraction de niveau G3 ou G4."},
{370,"Trafic d'influence","Monnayer une influence réelle ou supposée sur une décision publique ou judiciaire constitue une infraction lorsqu'un avantage indu est demandé ou reçu en échange."},
{371,"Sanctions ciblées","Les sanctions économiques doivent viser aussi précisément que possible les responsables, biens ou secteurs concernés afin de limiter les effets inutiles sur les civils."},
{372,"Base légale des sanctions","Aucun embargo, gel d'avoirs ou restriction commune ne peut être imposé au nom de l'Union sans décision adoptée par l'organe compétent selon la procédure applicable."},
{373,"Publication des sanctions","Toute sanction commune indique ses destinataires, son champ matériel, sa date d'effet, sa durée ou ses conditions de réexamen et les exceptions autorisées."},
{374,"Gel d'avoirs","Le gel empêche temporairement le transfert ou l'utilisation de certains avoirs identifiés sans en transférer automatiquement la propriété à l'autorité qui l'ordonne."},
{375,"Confiscation après jugement","La confiscation définitive d'avoirs exige une décision judiciaire ou une procédure équivalente offrant des garanties suffisantes aux propriétaires et tiers de bonne foi."},
{376,"Contournement de sanctions","Organiser sciemment un montage destiné à dissimuler le bénéficiaire ou la destination réelle d'une opération interdite constitue une violation distincte."},
{377,"Exceptions humanitaires","Les régimes de sanctions prévoient des exceptions raisonnables pour la nourriture, les soins, l'évacuation, l'aide humanitaire et les autres besoins civils essentiels."},
{378,"Fraude à la monnaie","Fabriquer, reproduire ou modifier une monnaie ou un crédit officiel dans le but de le faire accepter comme authentique constitue une infraction de niveau G3 à G5 selon l'ampleur."},
{379,"Manipulation des registres bancaires","Altérer sans autorisation un solde, une dette, une transaction ou un historique financier officiel constitue une infraction de niveau G4."},
{380,"Audit financier international","Lorsqu'une affaire concerne des fonds communs ou des sanctions, la Cour peut ordonner un audit ciblé et proportionné des comptes pertinents sous garanties de confidentialité."},
{381,"Responsabilité des organisations","Une entreprise ou organisation peut engager sa responsabilité lorsqu'une infraction est commise pour son compte par un dirigeant ou résulte d'un défaut grave de contrôle institutionnel."},
{382,"Responsabilité des dirigeants","La responsabilité de l'organisation n'exclut pas celle des dirigeants ou agents ayant personnellement ordonné, autorisé ou commis les faits."},
{383,"Programmes de conformité","L'existence de règles internes sérieuses de prévention, de contrôle et de signalement peut être prise en compte pour apprécier la diligence d'une organisation."},
{384,"Entreprise écran","Créer ou utiliser une entité sans activité réelle principalement afin de dissimuler un bénéficiaire, contourner une sanction ou faciliter une infraction constitue une circonstance aggravante."},
{385,"Bénéficiaire effectif","Dans une enquête financière autorisée, une organisation peut être tenue d'identifier les personnes qui contrôlent réellement ses actifs ou décisions."},
{386,"Falsification comptable","Tenir sciemment une comptabilité fausse ou détruire des écritures afin de dissimuler une infraction constitue une violation de niveau G3 ou G4."},
{387,"Entente criminelle structurée","La participation consciente à une organisation durable créée principalement pour commettre des infractions graves constitue une infraction distincte lorsque la contribution est réelle et significative."},
{388,"Extorsion","Obtenir un bien, un paiement ou un avantage par menace grave, violence ou contrainte illégale constitue une infraction de niveau G3 ou G4."},
{389,"Racket institutionnel","Imposer régulièrement des paiements ou services sous menace de violence ou d'abus de pouvoir constitue une circonstance aggravante de l'extorsion."},
{390,"Contrebande","Organiser le transport clandestin de biens dont l'importation, l'exportation ou la détention est légalement interdite constitue une infraction proportionnée à la nature des biens et à l'ampleur du trafic."},
{391,"Trafic d'armes prohibé","Fournir sciemment des armes ou matériels expressément interdits à une personne ou entité visée par un embargo constitue une infraction de niveau G4 ou G5."},
{392,"Financement d'un groupe criminel","Fournir sciemment des ressources substantielles à une organisation dans le but de faciliter ses crimes engage la responsabilité du financeur."},
{393,"Mercenariat illicite","Le recrutement de combattants privés n'est pas en soi interdit, mais l'organisation de forces rémunérées destinées à commettre des crimes ou à contourner une interdiction de guerre engage la responsabilité de leurs commanditaires."},
{394,"Sociétés militaires privées","Toute société fournissant des services armés à un membre demeure soumise au Code et doit disposer d'une chaîne de responsabilité identifiable."},
{395,"Corruption transnationale","La corruption impliquant plusieurs États, une institution de l'Union ou des fonds internationaux relève de la compétence commune lorsque les autres conditions sont remplies."},
{396,"Protection des lanceurs d'alerte","Une personne signalant de bonne foi une corruption ou fraude grave bénéficie d'une protection contre les représailles illégales, sans immunité pour ses propres infractions indépendantes."},
{397,"Obstruction à un audit","Détruire des documents, masquer volontairement des comptes ou menacer un auditeur dans une procédure autorisée constitue une infraction distincte."},
{398,"Dissolution judiciaire","Une organisation créée principalement pour commettre des infractions graves peut être dissoute sur décision judiciaire lorsque des mesures moins sévères seraient manifestement insuffisantes."},
{399,"Administration provisoire","La Cour peut, dans des cas exceptionnels, placer temporairement certains actifs d'une organisation sous administration contrôlée afin d'éviter leur disparition pendant une procédure."},
{400,"Droits des tiers de bonne foi","Les employés, créanciers et propriétaires non impliqués doivent être protégés autant que possible contre les conséquences inutiles d'une sanction visant une organisation criminelle."},
}
